openapi: 3.0.0
info:
  title: Appointment Service API
  description: API documentation for the Appointment Service
  version: v1
servers:
  - url: http://localhost:8005/api
paths:
  /appointments/:
    get:
      operationId: appointments_list
      description: List all appointments with pagination
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of appointments list
          content:
            application/json:
              schema:
                type: object
                required:
                  - count
                  - results
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                    format: uri
                    nullable: true
                  previous:
                    type: string
                    format: uri
                    nullable: true
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Appointment'
      tags:
        - appointments
      security:
        - BasicAuth: []
    post:
      operationId: appointments_create
      description: Create a new appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '201':
          description: Appointment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
      tags:
        - appointments
      security:
        - BasicAuth: []
  /appointments/{id}/:
    parameters:
      - name: id
        in: path
        description: A UUID string identifying this appointment.
        required: true
        schema:
          type: string
          format: uuid
    get:
      operationId: appointments_read
      description: Retrieve a specific appointment
      responses:
        '200':
          description: Successful retrieval of appointment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
      tags:
        - appointments
      security:
        - BasicAuth: []
    put:
      operationId: appointments_update
      description: Update all fields of an appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '200':
          description: Appointment updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
      tags:
        - appointments
      security:
        - BasicAuth: []
    patch:
      operationId: appointments_partial_update
      description: Update specific fields of an appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '200':
          description: Appointment partially updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
      tags:
        - appointments
      security:
        - BasicAuth: []
    delete:
      operationId: appointments_delete
      description: Delete an appointment
      responses:
        '204':
          description: Appointment deleted successfully
      tags:
        - appointments
      security:
        - BasicAuth: []
  /appointments/{id}/cancel/:
    parameters:
      - name: id
        in: path
        description: A UUID string identifying this appointment.
        required: true
        schema:
          type: string
          format: uuid
    post:
      operationId: appointments_cancel
      description: Cancel an appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '201':
          description: Appointment cancelled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
      tags:
        - appointments
      security:
        - BasicAuth: []
  /appointments/{id}/complete/:
    parameters:
      - name: id
        in: path
        description: A UUID string identifying this appointment.
        required: true
        schema:
          type: string
          format: uuid
    post:
      operationId: appointments_complete
      description: Mark an appointment as completed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '201':
          description: Appointment marked as completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
      tags:
        - appointments
      security:
        - BasicAuth: []
  /appointments/{id}/confirm/:
    parameters:
      - name: id
        in: path
        description: A UUID string identifying this appointment.
        required: true
        schema:
          type: string
          format: uuid
    post:
      operationId: appointments_confirm
      description: Confirm an appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '201':
          description: Appointment confirmed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
      tags:
        - appointments
      security:
        - BasicAuth: []
components:
  schemas:
    Appointment:
      type: object
      required:
        - patient_id
        - doctor_id
        - date
        - time
        - service_type
      properties:
        id:
          title: Id
          type: string
          format: uuid
          readOnly: true
        patient_id:
          title: Patient id
          type: string
          format: uuid
        doctor_id:
          title: Doctor id
          type: string
          format: uuid
        date:
          title: Date
          type: string
          format: date
        time:
          title: Time
          type: string
        status:
          title: Status
          type: string
          enum:
            - pending
            - confirmed
            - cancelled
            - completed
        created_at:
          title: Created at
          type: string
          format: date-time
          readOnly: true
        updated_at:
          title: Updated at
          type: string
          format: date-time
          readOnly: true
        notes:
          title: Notes
          type: string
          nullable: true
        service_type:
          title: Service type
          type: string
          maxLength: 100
          minLength: 1
        duration:
          title: Duration
          type: integer
          maximum: 240
          minimum: 15
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []