version: '3.9'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s

  postgres_db:
    image: postgres:13
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Core Services
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    volumes:
      - ./gateway/src:/etc/nginx/conf.d
    depends_on:
      - user_service
      - doctor_service
      - patient-service
      - appointment_service
      - chatbot_service

  user_service:
    build: ./services/user_service
    container_name: user_service
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./services/user_service:/app
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_DB=user_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
    depends_on:
      postgres_db:
        condition: service_healthy

  # Main Healthcare Services
  doctor_service:
    build: ./services/doctor_service
    container_name: doctor_service
    command: bash -c "python manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./services/doctor_service:/app
    ports:
      - "8002:8000"
    environment:
      - DATABASE_HOST=mysql_db
      - DATABASE_PORT=3306
      - DATABASE_NAME=doctor_db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=123456
    depends_on:
      mysql_db:
        condition: service_healthy

  patient-service:
    build: ./services/patient_service
    container_name: patient-service
    command: bash -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./services/patient_service:/app
    ports:
      - "8003:8000"
    environment:
      - DATABASE_HOST=mysql_db
      - DATABASE_PORT=3306
      - DATABASE_NAME=patient_db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=123456
    depends_on:
      mysql_db:
        condition: service_healthy

  appointment_service:
    build: ./services/appointment_service
    container_name: appointment_service
    command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./services/appointment_service:/app
    ports:
      - "8004:8000"
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    depends_on:
      mongodb:
        condition: service_healthy

  laboratory_service:
    build: ./services/laboratory_service
    container_name: laboratory_service
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./services/laboratory_service:/app
    ports:
      - "8005:8000"
    depends_on:
      - mysql_db
      - mongodb

  chatbot_service:
    build: ./services/chatbot_service
    container_name: chatbot_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/chatbot_service:/app
    ports:
      - "8006:8000"
    depends_on:
      - doctor_service
      - patient-service
      - appointment_service

volumes:
  mysql_data:
  mongodb_data:
  postgres_data: