# Generated by Django 4.2.21 on 2025-06-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_id_alter_doctor_user_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
